service: whos-that-pokemon-ui

plugins:
  - serverless-s3-sync

custom:
  siteName: whosthatpokemon.xyz
  aliasDNSName: s3-website-us-east-1.amazonaws.com
  aliasHostedZoneId: Z2O1EMRO9K5GLX
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: public

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs6.10


resources:
  Resources:
#    DnsRecord:
#      Type: "AWS::Route53::RecordSet"
#      Properties:
#        AliasTarget:
#          DNSName: ${self:custom.aliasDNSName}
#          HostedZoneId: ${self:custom.aliasHostedZoneId}
#        HostedZoneName: ${self:custom.siteName}.
#        Name:
#          Ref: StaticSite
#        Type: 'A'
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                  "arn:aws:s3:::",
                  {
                    "Ref": "StaticSite"
                  },
                  "/*"
                ]
                ]